### ISSUE TITLE
job errors not being displayed 

### ISSUE THREAD

**Issue by antgonza** [biocore/qiita#1228]
When an error while preprocessing or processing data and an error occurs the actual error message gets lost and only: `AttributeError: 'AsyncResult' object has no attribute 'pyout'` is shown.

**Comment by josenavas** [comment]
Taking a look right now

**Comment by josenavas** [comment]
the problem is in the server. The ipython version has been updated to 3.1.0 which is currently not supported. we need to downgrade Ipython until we fix the code base to work with Ipython 3.1.0

**Comment by antgonza** [comment]
That's correct and is working again after: `pip install ipython[all]==2.4.1`.
